# Generated by Django 4.2.6 on 2023-11-06 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appLOTR", "0002_pelicula_imagen_raza_actitud_raza_aspecto_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="raza",
            old_name="aspecto",
            new_name="caracteristica",
        ),
    ]
