# Generated by Django 4.2.6 on 2023-11-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appLOTR', '0003_rename_aspecto_raza_caracteristica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaje',
            old_name='pelicula',
            new_name='peliculas',
        ),
    ]
