# Generated by Django 4.2.6 on 2023-12-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appLOTR", "0004_rename_pelicula_personaje_peliculas"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaje",
            name="colorOjos_en",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="personaje",
            name="colorOjos_es",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="personaje",
            name="genero_en",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="personaje",
            name="genero_es",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="personaje",
            name="nombre_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="personaje",
            name="nombre_es",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
