# Generated by Django 4.2.6 on 2023-12-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appLOTR", "0005_personaje_colorojos_en_personaje_colorojos_es_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="raza",
            old_name="tamnyo",
            new_name="tamanyo",
        ),
        migrations.RemoveField(
            model_name="personaje",
            name="nombre_en",
        ),
        migrations.RemoveField(
            model_name="personaje",
            name="nombre_es",
        ),
        migrations.AddField(
            model_name="pelicula",
            name="genero_en",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="pelicula",
            name="genero_es",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="pelicula",
            name="titulo_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pelicula",
            name="titulo_es",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="personaje",
            name="colorPelo_en",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="personaje",
            name="colorPelo_es",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="raza",
            name="actitud_en",
            field=models.CharField(default="null", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="raza",
            name="actitud_es",
            field=models.CharField(default="null", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="raza",
            name="caracteristica_en",
            field=models.CharField(default="null", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="raza",
            name="caracteristica_es",
            field=models.CharField(default="null", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="raza",
            name="longevidad_en",
            field=models.CharField(default="null", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="raza",
            name="longevidad_es",
            field=models.CharField(default="null", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="raza",
            name="tamanyo_en",
            field=models.CharField(default="null", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="raza",
            name="tamanyo_es",
            field=models.CharField(default="null", max_length=20, null=True),
        ),
    ]
