# Generated by Django 4.2.6 on 2023-12-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appLOTR", "0006_rename_tamnyo_raza_tamanyo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="raza",
            name="nombre_en",
            field=models.CharField(default="null", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="raza",
            name="nombre_es",
            field=models.CharField(default="null", max_length=20, null=True),
        ),
    ]
