# Generated by Django 4.2.6 on 2023-12-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appLOTR", "0007_raza_nombre_en_raza_nombre_es"),
    ]

    operations = [
        migrations.AddField(
            model_name="pelicula",
            name="genero_eus",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="pelicula",
            name="titulo_eus",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="personaje",
            name="colorOjos_eus",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="personaje",
            name="colorPelo_eus",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="personaje",
            name="genero_eus",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="raza",
            name="actitud_eus",
            field=models.CharField(default="null", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="raza",
            name="caracteristica_eus",
            field=models.CharField(default="null", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="raza",
            name="longevidad_eus",
            field=models.CharField(default="null", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="raza",
            name="nombre_eus",
            field=models.CharField(default="null", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="raza",
            name="tamanyo_eus",
            field=models.CharField(default="null", max_length=20, null=True),
        ),
    ]
